### ISSUE TITLE
unescaped attributes

### ISSUE THREAD

**Issue by vtsyganov** [slime-lang/slime#88] opened 2016-01-15 00:15 UTC
Hi. Is there a way to avoid escaping of an attribute? Slim has '==' for that but looks like it doesn't work in Slime

**Comment by lpil** [comment] 2016-01-15 00:47
Sorry, could you give an example?

**Comment by vtsyganov** [comment] 2016-01-15 01:03
Sure. For example, I want to create a script tag with content window.userToken = 'some_token'
How I should do that? 
Command: script == "window.userToken = '#{token}'" 
Result: `<script>window.userToken = &#39;some_token&#39;</script>`

**Comment by doomspork** [comment] 2016-01-15 01:55
@vtsyganov what version are you using?  This is what I get:

``` elixir
iex> slime = """
...> script == "window.userToken = '\#{token}'"
...> """
"script == \"window.userToken = '\#{token}'\"\n"
iex> Slime.render(slime, [token: "some_token"])
"<script>window.userToken = 'some_token'</script>"
```

**Comment by Rakoth** [comment] 2016-01-15 06:44
I believe, the problem is with engine: Phoenix.HTML.Engine

**Comment by doomspork** [comment] 2016-03-18 16:16
Sounds like this isn't a Slime issue so I'm going to close this.  If this comes up again we can create an issue and take another look.

**Closed as completed by doomspork** 2016-03-18 16:16 UTC
