### ISSUE TITLE
Dialyzer warnings

### ISSUE THREAD

**Issue by waiting-for-dev** [slime-lang/slime#133] opened 2017-06-22 09:17 UTC
Not sure if I should report this issue here, in `phoenix_slime` or in `phoenix`, but I can't reproduce the issue with `eex` templates, so I suspect it has to be related with `slime`. Apologies beforehand if I'm wrong or if I'm misunderstanding something, because I'm quite new to Elixir & Phoenix.

While running `dialyzer`, I get following warnings for all (except one, weirdly) slime templates:

```
web/templates/layout/app.html.slime:1: Guard test 'or'('false','false') can never succeed
web/templates/layout/app.html.slime:1: The test bitstring() == 'true' can never evaluate to 'true'
```

Please, tell me if you need some other debugging information.

Thanks

**Comment by little-bobby-tables** [comment] 2017-06-22 11:41
A file with just
```
div data-content="text and #{some_binary}"
```
or
```
div data-content="text and number #{3}"
```
emits these warnings for me, too.

I think they are caused by [the code Slime injects](https://github.com/slime-lang/slime/blob/master/lib/slime/compiler.ex#L71) for attribute values, or, to be precise, the way Slime decides when to inject it. The check is fairly naive and doesn't take into account the types of bindings — generating the wrapping code for e.g.`bitstring`, which can never evaluate  to `false`.

I'm not sure if there's an easy fix for this.

**Comment by Rakoth** [comment] 2017-06-28 06:27
I will look into this

**Comment by Rakoth** [comment] 2017-06-28 16:20
I am not sure about test case for this issue, should I add one? @little-bobby-tables @doomspork

**Closed as completed** 2017-07-07 15:30 UTC
